### ISSUE TITLE
Misc UI fixes

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly-ui#167]
Performance:

- [x] Check re-rendering is reasonable
- [x] Page API calls should be optimized
- [x] Slideover API calls should be optimized

Timeline:

- [x] Remove histogram from Timeline page
- [x] Timeline should be more responsive on smaller screens (#172)

Theming:

- [x] Border radiuses should be consistent
- [x] Small cards should be left aligned
- [x] Histogram popover should be formatted better
- [x] Filter modal and chips should match theming of application

Time Range:
- [x] Start/Stop time support in query params (#173)

Miscellaneous:

- [x] Loading and empty states should be consistent across all pages
- [x] Loading and empty states should be consistent across all slideovers
- [x] Add Cmd + Click support for links (#174)
- [x] Responsive sidebar (#175)
- [x] Operation accordion should have a link out to the operation
- [x] Groups page: Show member identities in table view
- [x] MyNode diagram should not be draggable
- [x] Websockets should indicate if the connection is current UI that is being viewed (#169)
- [x] Transfers tables should show pool name in second column (#166 )
- [x] Balance Slide should show token index if token type is nonfungible (pool, token index, uri, balance)
- [x] Transaction Slide should give a link-out button for each Operation
- [x] My Node should show token "plugin type" (ie "fftokens") in addition to configured name
- [x] Hovering over relative time should show full timestamp
- [x] All events should be up to date with FireFly core events
- [x] All filters should be consistent with FireFly core filter factories
